//go:build windows

package windows

type KeyboardKeys int

const (
	KEY_LBUTTON             KeyboardKeys = 0x01 //	Left mouse button
	KEY_RBUTTON             KeyboardKeys = 0x02 //	Right mouse button
	KEY_CANCEL              KeyboardKeys = 0x03 //	Control-break processing
	KEY_MBUTTON             KeyboardKeys = 0x04 //	Middle mouse button
	KEY_XBUTTON1            KeyboardKeys = 0x05 //	X1 mouse button
	KEY_XBUTTON2            KeyboardKeys = 0x06 //	X2 mouse button
	KEY_BACK                KeyboardKeys = 0x08 //	Backspace key
	KEY_TAB                 KeyboardKeys = 0x09 //	Tab key
	KEY_CLEAR               KeyboardKeys = 0x0C //	Clear key
	KEY_RETURN              KeyboardKeys = 0x0D //	Enter key
	KEY_SHIFT               KeyboardKeys = 0x10 //	Shift key
	KEY_CONTROL             KeyboardKeys = 0x11 //	Ctrl key
	KEY_MENU                KeyboardKeys = 0x12 //	Alt key
	KEY_PAUSE               KeyboardKeys = 0x13 //	Pause key
	KEY_CAPITAL             KeyboardKeys = 0x14 //	Caps lock key
	KEY_KANA                KeyboardKeys = 0x15 //	IME Kana mode
	KEY_HANGUL              KeyboardKeys = 0x15 //	IME Hangul mode
	KEY_IME_ON              KeyboardKeys = 0x16 //	IME On
	KEY_JUNJA               KeyboardKeys = 0x17 //	IME Junja mode
	KEY_FINAL               KeyboardKeys = 0x18 //	IME final mode
	KEY_HANJA               KeyboardKeys = 0x19 //	IME Hanja mode
	KEY_KANJI               KeyboardKeys = 0x19 //	IME Kanji mode
	KEY_IME_OFF             KeyboardKeys = 0x1A //	IME Off
	KEY_ESCAPE              KeyboardKeys = 0x1B //	Esc key
	KEY_CONVERT             KeyboardKeys = 0x1C //	IME convert
	KEY_NONCONVERT          KeyboardKeys = 0x1D //	IME nonconvert
	KEY_ACCEPT              KeyboardKeys = 0x1E //	IME accept
	KEY_MODECHANGE          KeyboardKeys = 0x1F //	IME mode change request
	KEY_SPACE               KeyboardKeys = 0x20 //	Spacebar key
	KEY_PRIOR               KeyboardKeys = 0x21 //	Page up key
	KEY_NEXT                KeyboardKeys = 0x22 //	Page down key
	KEY_END                 KeyboardKeys = 0x23 //	End key
	KEY_HOME                KeyboardKeys = 0x24 //	Home key
	KEY_LEFT                KeyboardKeys = 0x25 //	Left arrow key
	KEY_UP                  KeyboardKeys = 0x26 //	Up arrow key
	KEY_RIGHT               KeyboardKeys = 0x27 //	Right arrow key
	KEY_DOWN                KeyboardKeys = 0x28 //	Down arrow key
	KEY_SELECT              KeyboardKeys = 0x29 //	Select key
	KEY_PRINT               KeyboardKeys = 0x2A //	Print key
	KEY_EXECUTE             KeyboardKeys = 0x2B //	Execute key
	KEY_SNAPSHOT            KeyboardKeys = 0x2C //	Print screen key
	KEY_INSERT              KeyboardKeys = 0x2D //	Insert key
	KEY_DELETE              KeyboardKeys = 0x2E //	Delete key
	KEY_HELP                KeyboardKeys = 0x2F //	Help key
	KEY_0                   KeyboardKeys = 0x30 //	0 key
	KEY_1                   KeyboardKeys = 0x31 //	1 key
	KEY_2                   KeyboardKeys = 0x32 //	2 key
	KEY_3                   KeyboardKeys = 0x33 //	3 key
	KEY_4                   KeyboardKeys = 0x34 //	4 key
	KEY_5                   KeyboardKeys = 0x35 //	5 key
	KEY_6                   KeyboardKeys = 0x36 //	6 key
	KEY_7                   KeyboardKeys = 0x37 //	7 key
	KEY_8                   KeyboardKeys = 0x38 //	8 key
	KEY_9                   KeyboardKeys = 0x39 //	9 key
	KEY_A                   KeyboardKeys = 0x41 //	A key
	KEY_B                   KeyboardKeys = 0x42 //	B key
	KEY_C                   KeyboardKeys = 0x43 //	C key
	KEY_D                   KeyboardKeys = 0x44 //	D key
	KEY_E                   KeyboardKeys = 0x45 //	E key
	KEY_F                   KeyboardKeys = 0x46 //	F key
	KEY_G                   KeyboardKeys = 0x47 //	G key
	KEY_H                   KeyboardKeys = 0x48 //	H key
	KEY_I                   KeyboardKeys = 0x49 //	I key
	KEY_J                   KeyboardKeys = 0x4A //	J key
	KEY_K                   KeyboardKeys = 0x4B //	K key
	KEY_L                   KeyboardKeys = 0x4C //	L key
	KEY_M                   KeyboardKeys = 0x4D //	M key
	KEY_N                   KeyboardKeys = 0x4E //	N key
	KEY_O                   KeyboardKeys = 0x4F //	O key
	KEY_P                   KeyboardKeys = 0x50 //	P key
	KEY_Q                   KeyboardKeys = 0x51 //	Q key
	KEY_R                   KeyboardKeys = 0x52 //	R key
	KEY_S                   KeyboardKeys = 0x53 //	S key
	KEY_T                   KeyboardKeys = 0x54 //	T key
	KEY_U                   KeyboardKeys = 0x55 //	U key
	KEY_V                   KeyboardKeys = 0x56 //	V key
	KEY_W                   KeyboardKeys = 0x57 //	W key
	KEY_X                   KeyboardKeys = 0x58 //	X key
	KEY_Y                   KeyboardKeys = 0x59 //	Y key
	KEY_Z                   KeyboardKeys = 0x5A //	Z key
	KEY_LWIN                KeyboardKeys = 0x5B //	Left Windows logo key
	KEY_RWIN                KeyboardKeys = 0x5C //	Right Windows logo key
	KEY_APPS                KeyboardKeys = 0x5D //	Application key
	KEY_SLEEP               KeyboardKeys = 0x5F //	Computer Sleep key
	KEY_NUMPAD0             KeyboardKeys = 0x60 //	Numeric keypad 0 key
	KEY_NUMPAD1             KeyboardKeys = 0x61 //	Numeric keypad 1 key
	KEY_NUMPAD2             KeyboardKeys = 0x62 //	Numeric keypad 2 key
	KEY_NUMPAD3             KeyboardKeys = 0x63 //	Numeric keypad 3 key
	KEY_NUMPAD4             KeyboardKeys = 0x64 //	Numeric keypad 4 key
	KEY_NUMPAD5             KeyboardKeys = 0x65 //	Numeric keypad 5 key
	KEY_NUMPAD6             KeyboardKeys = 0x66 //	Numeric keypad 6 key
	KEY_NUMPAD7             KeyboardKeys = 0x67 //	Numeric keypad 7 key
	KEY_NUMPAD8             KeyboardKeys = 0x68 //	Numeric keypad 8 key
	KEY_NUMPAD9             KeyboardKeys = 0x69 //	Numeric keypad 9 key
	KEY_MULTIPLY            KeyboardKeys = 0x6A //	Multiply key
	KEY_ADD                 KeyboardKeys = 0x6B //	Add key
	KEY_SEPARATOR           KeyboardKeys = 0x6C //	Separator key
	KEY_SUBTRACT            KeyboardKeys = 0x6D //	Subtract key
	KEY_DECIMAL             KeyboardKeys = 0x6E //	Decimal key
	KEY_DIVIDE              KeyboardKeys = 0x6F //	Divide key
	KEY_F1                  KeyboardKeys = 0x70 //	F1 key
	KEY_F2                  KeyboardKeys = 0x71 //	F2 key
	KEY_F3                  KeyboardKeys = 0x72 //	F3 key
	KEY_F4                  KeyboardKeys = 0x73 //	F4 key
	KEY_F5                  KeyboardKeys = 0x74 //	F5 key
	KEY_F6                  KeyboardKeys = 0x75 //	F6 key
	KEY_F7                  KeyboardKeys = 0x76 //	F7 key
	KEY_F8                  KeyboardKeys = 0x77 //	F8 key
	KEY_F9                  KeyboardKeys = 0x78 //	F9 key
	KEY_F10                 KeyboardKeys = 0x79 //	F10 key
	KEY_F11                 KeyboardKeys = 0x7A //	F11 key
	KEY_F12                 KeyboardKeys = 0x7B //	F12 key
	KEY_F13                 KeyboardKeys = 0x7C //	F13 key
	KEY_F14                 KeyboardKeys = 0x7D //	F14 key
	KEY_F15                 KeyboardKeys = 0x7E //	F15 key
	KEY_F16                 KeyboardKeys = 0x7F //	F16 key
	KEY_F17                 KeyboardKeys = 0x80 //	F17 key
	KEY_F18                 KeyboardKeys = 0x81 //	F18 key
	KEY_F19                 KeyboardKeys = 0x82 //	F19 key
	KEY_F20                 KeyboardKeys = 0x83 //	F20 key
	KEY_F21                 KeyboardKeys = 0x84 //	F21 key
	KEY_F22                 KeyboardKeys = 0x85 //	F22 key
	KEY_F23                 KeyboardKeys = 0x86 //	F23 key
	KEY_F24                 KeyboardKeys = 0x87 //	F24 key
	KEY_NUMLOCK             KeyboardKeys = 0x90 //	Num lock key
	KEY_SCROLL              KeyboardKeys = 0x91 //	Scroll lock key
	KEY_LSHIFT              KeyboardKeys = 0xA0 //	Left Shift key
	KEY_RSHIFT              KeyboardKeys = 0xA1 //	Right Shift key
	KEY_LCONTROL            KeyboardKeys = 0xA2 //	Left Ctrl key
	KEY_RCONTROL            KeyboardKeys = 0xA3 //	Right Ctrl key
	KEY_LMENU               KeyboardKeys = 0xA4 //	Left Alt key
	KEY_RMENU               KeyboardKeys = 0xA5 //	Right Alt key
	KEY_BROWSER_BACK        KeyboardKeys = 0xA6 //	Browser Back key
	KEY_BROWSER_FORWARD     KeyboardKeys = 0xA7 //	Browser Forward key
	KEY_BROWSER_REFRESH     KeyboardKeys = 0xA8 //	Browser Refresh key
	KEY_BROWSER_STOP        KeyboardKeys = 0xA9 //	Browser Stop key
	KEY_BROWSER_SEARCH      KeyboardKeys = 0xAA //	Browser Search key
	KEY_BROWSER_FAVORITES   KeyboardKeys = 0xAB //	Browser Favorites key
	KEY_BROWSER_HOME        KeyboardKeys = 0xAC //	Browser Start and Home key
	KEY_VOLUME_MUTE         KeyboardKeys = 0xAD //	Volume Mute key
	KEY_VOLUME_DOWN         KeyboardKeys = 0xAE //	Volume Down key
	KEY_VOLUME_UP           KeyboardKeys = 0xAF //	Volume Up key
	KEY_MEDIA_NEXT_TRACK    KeyboardKeys = 0xB0 //	Next Track key
	KEY_MEDIA_PREV_TRACK    KeyboardKeys = 0xB1 //	Previous Track key
	KEY_MEDIA_STOP          KeyboardKeys = 0xB2 //	Stop Media key
	KEY_MEDIA_PLAY_PAUSE    KeyboardKeys = 0xB3 //	Play/Pause Media key
	KEY_LAUNCH_MAIL         KeyboardKeys = 0xB4 //	Start Mail key
	KEY_LAUNCH_MEDIA_SELECT KeyboardKeys = 0xB5 //	Select Media key
	KEY_LAUNCH_APP1         KeyboardKeys = 0xB6 //	Start Application 1 key
	KEY_LAUNCH_APP2         KeyboardKeys = 0xB7 //	Start Application 2 key
	KEY_OEM_1               KeyboardKeys = 0xBA //	It can vary by keyboard. For the US ANSI keyboard , the Semiсolon and Colon key
	KEY_OEM_PLUS            KeyboardKeys = 0xBB //	For any country/region, the Equals and Plus key
	KEY_OEM_COMMA           KeyboardKeys = 0xBC //	For any country/region, the Comma and Less Than key
	KEY_OEM_MINUS           KeyboardKeys = 0xBD //	For any country/region, the Dash and Underscore key
	KEY_OEM_PERIOD          KeyboardKeys = 0xBE //	For any country/region, the Period and Greater Than key
	KEY_OEM_2               KeyboardKeys = 0xBF //	It can vary by keyboard. For the US ANSI keyboard, the Forward Slash and Question Mark key
	KEY_OEM_3               KeyboardKeys = 0xC0 //	It can vary by keyboard. For the US ANSI keyboard, the Grave Accent and Tilde key
	KEY_OEM_4               KeyboardKeys = 0xDB //	It can vary by keyboard. For the US ANSI keyboard, the Left Brace key
	KEY_OEM_5               KeyboardKeys = 0xDC //	It can vary by keyboard. For the US ANSI keyboard, the Backslash and Pipe key
	KEY_OEM_6               KeyboardKeys = 0xDD //	It can vary by keyboard. For the US ANSI keyboard, the Right Brace key
	KEY_OEM_7               KeyboardKeys = 0xDE //	It can vary by keyboard. For the US ANSI keyboard, the Apostrophe and Double Quotation Mark key
	KEY_OEM_8               KeyboardKeys = 0xDF //	It can vary by keyboard. For the Canadian CSA keyboard, the Right Ctrl key
	KEY_OEM_102             KeyboardKeys = 0xE2 //	It can vary by keyboard. For the European ISO keyboard, the Backslash and Pipe key
	KEY_PROCESSKEY          KeyboardKeys = 0xE5 //	IME PROCESS key
	KEY_ATTN                KeyboardKeys = 0xF6 //	Attn key
	KEY_CRSEL               KeyboardKeys = 0xF7 //	CrSel key
	KEY_EXSEL               KeyboardKeys = 0xF8 //	ExSel key
	KEY_EREOF               KeyboardKeys = 0xF9 //	Erase EOF key
	KEY_PLAY                KeyboardKeys = 0xFA //	Play key
	KEY_ZOOM                KeyboardKeys = 0xFB //	Zoom key
	KEY_PA1                 KeyboardKeys = 0xFD //	PA1 key
	KEY_OEM_CLEAR           KeyboardKeys = 0xFE //	Clear key
)
